### PR TITLE
Add tests and switch to "loose-envify"

### PR DESCRIPTION
**Pull request by zertosh**
Hey @BerkeleyTrue, I added some tests and switched to loose-envify. loose-envify is faster lighter version of envify for use with small libraries like this. When you publish this, please don't bump the major version, it'll cause a lot of downstream dependencies to have to update – a bump in minor or patch version should be sufficient. Thanks in advanced!

### CODE REVIEW

**Comment by zertosh** [comment]
ping @BerkeleyTrue

**Comment by BerkeleyTrue** [comment]
@zertosh Thanks! I'll release this as a minor update.

**Comment by zertosh** [comment]
np! can you publish it to npm?

**Comment by BerkeleyTrue** [comment]
Sorry about that. Published as 2.1.0

**Comment by zertosh** [comment]
np - thanks again!

**Pull request merged**
