### PR TITLE
Remove "browser" version

### PR DESCRIPTION
**Pull request by TrySound**
Ref #18

Since the problem with uglify is fixed there is not reason to keep
browser version which do not add any benefits. Actually it blocks us
from distributing `esm` version which is widely used these days and
supported by the most popular bundlers like webpack, rollup and parcel.

Here's a few links
https://github.com/facebook/fbjs/pull/86#issuecomment-285204734

Both uglify and babel minify support evaulation and eliminating

```js
(function () {
  function warning() {}

  var __DEV__ = 'production' !== 'production'

  if (__DEV__) {
    warning = function (msg) {
      console.log(msg)
    }
  }

  warning()
} ());
```

https://skalman.github.io/UglifyJS-online/

https://babeljs.io/repl#?babili=true&browsers=&build=&builtIns=false&code_lz=BQMwrgdgxgLglgewgAmASmQbwFDOeaeJZAdwEMAnCOCAc3SwF9tdkA3S5AfS4BEBRAGo9kAXmQByAA4UEAEzCxEECcgCEo8dNkKlSCSzxwQqHgOFcMOPHnJUatMfkh6UwALYBnWldY3kUEieCAA2AKYAdCEI9F4-fsjMeMysdtR06NiMqGhoANxAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&lineWrap=false&presets=babili%2Cenv&prettier=false&targets=&version=6.26.0&envVersion=1.6.2

### CODE REVIEW

**Comment by TrySound** [comment]
@BerkeleyTrue friendly ping. If you are busy are could help to maintain this project.

**Comment by TrySound** [comment]
@BerkeleyTrue Sorry for noise but I would like to get your feedback.

**Comment by BerkeleyTrue** [comment]
@TrySound thanks for the pin. I say the first one a couple of days ago but I've been buried in a personal project. This is on my list.

@zertosh I'm pretty sure you where the original committer for these files. I see you are still have the browser version of invariant in your package. I'd appreciate it if you could take a quick glance here. I don't remember the specifics of that issue. Thanks.

**Comment by TrySound** [comment]
Friendly ping @zertosh . Would be good to see your opinion.

**Comment by zertosh** [comment]
👍

**Comment by BerkeleyTrue** [comment]
@TrySound I will be review this pr later tonight.

**Comment by BerkeleyTrue** [comment]
fixed in 521f5f5dd7bc264059e88e4d7ec9ebc955fc3cba

**Comment by BerkeleyTrue** [comment]
released in https://github.com/BerkeleyTrue/warning/releases/tag/v4.0.0

**Pull request closed without merging**
