### PR TITLE
Sync code with fbjs to fix a bug

### PR DESCRIPTION
**Pull request by realityking**
I tried using this package in create-react-context (see https://github.com/jamiebuilds/create-react-context/pull/22) and discovered a bug compared to fbjs.

This line would not work correctly:

```js
warning(
  (changedBits & MAX_SIGNED_31_BIT_INT) === changedBits,
  'calculateChangedBits: Expected the return value to be a ' +
  '31-bit integer. Instead received: %s',
  changedBits
);
````

Since it did work in fbjs I simply resented the code. I also removed to react-isms in follow-up commits.

### CODE REVIEW

**Comment by realityking** [comment]
Build failure will be fixed with #31

**Comment by BerkeleyTrue** [comment]
Why won't this code work? What's the value of `changedBits` and `MAX_SIGNED_31_BIT_INT`?

**Comment by realityking** [comment]
@BerkeleyTrue I didn't fully debug it. My first attempt was simply to check if the upstream implementation in fbjs had the same issue. Since it doesn't, is it really worth understanding why they behave differently?

**Comment by BerkeleyTrue** [comment]
It may have been a bug introduced a couple of months ago. A fix has been released as https://github.com/BerkeleyTrue/warning/releases/tag/v4.0.3

Happy Coding

**Comment by realityking** [comment]
@BerkeleyTrue That did indeed fix things. Thank you!

**Pull request closed without merging**
